version: '3.8'

services:
  mysql-dev:
    container_name: mysql-dev
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: parsa
      MYSQL_PASSWORD: notparsa
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: